CREATE DATABASE TwitterDB;
USE TwitterDB

CREATE TABLE Users(
	UserID int NOT NULL PRIMARY KEY IDENTITY(1,1),
	Username VARCHAR(50) NOT NULL UNIQUE,
	Email VARCHAR(50) NOT NULL UNIQUE,
	Name VARCHAR(50) NOT NULL,
	Bio VARCHAR(100) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	JoinDate DATETIME DEFAULT GETDATE()
	);

CREATE TABLE Tweet(
	TweetID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserID INT NOT NULL,
	Content VARCHAR(500) NOT NULL,
	Media VARCHAR(500),
	PostDate DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
	);
 
 CREATE TABLE Hashtag(
	HashtagID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Text VARCHAR(100) NOT NULL UNIQUE
	);

CREATE TABLE TweetHashtag(
	TweetID INT NOT NULL,
	HashtagID INT NOT NULL,
	PRIMARY KEY(TweetID, HashtagID),
	FOREIGN KEY (TweetID) REFERENCES Tweet(TweetID) ON DELETE CASCADE,
	FOREIGN KEY (HashtagID) REFERENCES Hashtag(HashtagID) ON DELETE CASCADE
	);

CREATE TABLE Follow(
	FollowerID INT NOT NULL,
	FollowedID INT NOT NULL,
	PRIMARY KEY (FollowerID, FollowedID),
	FOREIGN KEY (FollowerID) REFERENCES Users(UserID) ON DELETE NO ACTION,
	FOREIGN KEY (FollowedID) REFERENCES Users(UserID) ON DELETE CASCADE
	);

CREATE TABLE Mention(
	MentionID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserID INT NOT NULL,
	TweetID INT NOT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE NO ACTION,
	FOREIGN KEY (TweetID) REFERENCES Tweet(TweetID) ON DELETE CASCADE
	);

CREATE TABLE Reply(
	ReplyID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	UserID INT NOT NULL,
	TweetID INT NOT NULL,
	Content VARCHAR(500) NOT NULL,
	Media VARCHAR(500),
	PostDate DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (TweetID) REFERENCES Tweet(TweetID) ON DELETE NO ACTION,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
	);

